// Command opcodecatalog generates world packet constants and labels from
// AzerothCore's public Opcodes.h in tmp/client-data. It verifies the pinned
// header's checksum and never accesses the network or running server.
//
// Run from the repository root:
//
//	./run client-data:fetch
//	./run opcodecatalog:generate
package main

import (
	"bytes"
	"crypto/sha256"
	"errors"
	"fmt"
	"go/format"
	"os"
	"regexp"
	"strconv"
	"strings"

	"github.com/agent-wow/agent-wow/tools/internal/clientdata"
)

type entry struct {
	name, label string
	value       uint32
}

func main() {
	if len(os.Args) == 2 && (os.Args[1] == "--help" || os.Args[1] == "-h") {
		fmt.Println("Usage: ./run opcodecatalog:generate\nReads tmp/client-data/Opcodes.h and writes pkg/opcode/world_gen.go and pkg/opcode/world_names_gen.go. Run './run client-data:fetch' first.")
		return
	}
	if len(os.Args) != 1 {
		fmt.Fprintln(os.Stderr, "Usage: ./run opcodecatalog:generate")
		os.Exit(2)
	}
	if err := run(clientdata.Directory); err != nil {
		fmt.Fprintln(os.Stderr, "generate opcode catalog:", err)
		os.Exit(1)
	}
	fmt.Println("Generated pkg/opcode/world_gen.go and pkg/opcode/world_names_gen.go")
}

func run(directory string) error {
	data, err := clientdata.Read(directory, "Opcodes.h")
	if err != nil {
		return err
	}
	constants, names, err := generate(data)
	if err != nil {
		return err
	}
	if err := os.WriteFile("pkg/opcode/world_gen.go", constants, 0o644); err != nil {
		return err
	}
	return os.WriteFile("pkg/opcode/world_names_gen.go", names, 0o644)
}

func generate(data []byte) ([]byte, []byte, error) {
	if fmt.Sprintf("%x", sha256.Sum256(data)) != clientdata.OpcodesSHA256 {
		return nil, nil, fmt.Errorf("Opcodes.h checksum mismatch; run './run client-data:fetch' to fetch the header from %s", clientdata.OpcodesURL)
	}
	enum := regexp.MustCompile(`(?s)enum Opcodes : uint16\s*\{(.*?)\};`).FindSubmatch(data)
	if enum == nil {
		return nil, nil, errors.New("missing Opcodes enum")
	}
	assignment := regexp.MustCompile(`^([A-Z][A-Z0-9_]+)\s*=\s*(0x[0-9A-Fa-f]+)$`)
	entries := []entry{{"NullOpcode", "NULL_OPCODE", 0}}
	identifiers := map[string]bool{"NullOpcode": true, "NumMsgTypes": true}
	var limit uint32
	for _, line := range strings.Split(string(enum[1]), "\n") {
		line, _, _ = strings.Cut(line, "//")
		line = strings.TrimSuffix(strings.TrimSpace(line), ",")
		if line == "" {
			continue
		}
		match := assignment.FindStringSubmatch(line)
		if match == nil || limit != 0 {
			return nil, nil, fmt.Errorf("unexpected opcode definition %q", line)
		}
		value, err := strconv.ParseUint(match[2], 0, 16)
		if err != nil {
			return nil, nil, err
		}
		if value != uint64(len(entries)) {
			return nil, nil, fmt.Errorf("expected opcode 0x%03x, got %s", len(entries), match[2])
		}
		if match[1] == "NUM_MSG_TYPES" {
			limit = uint32(value)
			continue
		}
		name := goName(match[1])
		if identifiers[name] {
			return nil, nil, fmt.Errorf("duplicate Go identifier %s", name)
		}
		identifiers[name] = true
		entries = append(entries, entry{name, match[1], uint32(value)})
	}
	if limit == 0 {
		return nil, nil, errors.New("missing NUM_MSG_TYPES boundary")
	}
	if !regexp.MustCompile(`\bNULL_OPCODE\s*=\s*0x0000\b`).Match(data) {
		return nil, nil, errors.New("missing NULL_OPCODE definition")
	}
	var constants, names bytes.Buffer
	for _, out := range []*bytes.Buffer{&constants, &names} {
		fmt.Fprintln(out, "// Code generated by ./run opcodecatalog:generate; DO NOT EDIT.")
		fmt.Fprintln(out, "// WoW 3.3.5a, build 12340.")
		fmt.Fprintln(out, "// Source: "+clientdata.OpcodesURL)
		fmt.Fprintln(out, "// SHA-256: "+clientdata.OpcodesSHA256)
		fmt.Fprintln(out, "\npackage opcode")
	}
	fmt.Fprintln(&constants, "\n// World packet identifiers, including obsolete and server-specific entries.")
	fmt.Fprintln(&constants, "// An identifier being defined does not imply client or server support for it.")
	fmt.Fprintln(&constants, "const (")
	for _, op := range entries {
		fmt.Fprintf(&constants, "%s = 0x%03x // %s\n", op.name, op.value, op.label)
	}
	fmt.Fprintln(&constants, ")")
	fmt.Fprintln(&constants, "\n// NumMsgTypes is the exclusive upper bound of the catalog, not a packet opcode.")
	fmt.Fprintf(&constants, "const NumMsgTypes = 0x%03x\n", limit)
	fmt.Fprintln(&names, "\nvar worldNames = [...]string{")
	for _, op := range entries {
		fmt.Fprintf(&names, "%s: %q,\n", op.name, op.label)
	}
	fmt.Fprintln(&names, "}")
	world, err := format.Source(constants.Bytes())
	if err != nil {
		return nil, nil, err
	}
	labels, err := format.Source(names.Bytes())
	return world, labels, err
}

func goName(label string) string {
	parts := strings.Split(label, "_")
	for i, part := range parts {
		switch part {
		case "CMSG", "SMSG", "MSG", "UMSG", "TC9", "ID", "GUID", "AI", "GM", "NPC", "UI", "PVP", "PVE", "AFK", "DND", "LFG", "LFD", "LFR", "GMTICKET", "SRP6", "VOIP", "MOTD", "PCT", "XP":
		default:
			parts[i] = part[:1] + strings.ToLower(part[1:])
		}
	}
	return strings.Join(parts, "")
}
