// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.36.2
// source: internal/modulefixture/fixture.proto

package fixturev1

import (
	v1 "github.com/agent-wow/agent-wow/pkg/modules/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        uint64                 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Opcode        uint32                 `protobuf:"varint,3,opt,name=opcode,proto3" json:"opcode,omitempty"`
	Failure       string                 `protobuf:"bytes,4,opt,name=failure,proto3" json:"failure,omitempty"`
	DelayMs       uint32                 `protobuf:"varint,5,opt,name=delay_ms,json=delayMs,proto3" json:"delay_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_internal_modulefixture_fixture_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_internal_modulefixture_fixture_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_internal_modulefixture_fixture_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetNumber() uint64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Request) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Request) GetOpcode() uint32 {
	if x != nil {
		return x.Opcode
	}
	return 0
}

func (x *Request) GetFailure() string {
	if x != nil {
		return x.Failure
	}
	return ""
}

func (x *Request) GetDelayMs() uint32 {
	if x != nil {
		return x.DelayMs
	}
	return 0
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        uint64                 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	ClientTimeMs  uint32                 `protobuf:"varint,3,opt,name=client_time_ms,json=clientTimeMs,proto3" json:"client_time_ms,omitempty"`
	Packets       uint32                 `protobuf:"varint,4,opt,name=packets,proto3" json:"packets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_internal_modulefixture_fixture_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_internal_modulefixture_fixture_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_internal_modulefixture_fixture_proto_rawDescGZIP(), []int{1}
}

func (x *Result) GetNumber() uint64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Result) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Result) GetClientTimeMs() uint32 {
	if x != nil {
		return x.ClientTimeMs
	}
	return 0
}

func (x *Result) GetPackets() uint32 {
	if x != nil {
		return x.Packets
	}
	return 0
}

var File_internal_modulefixture_fixture_proto protoreflect.FileDescriptor

const file_internal_modulefixture_fixture_proto_rawDesc = "" +
	"\n" +
	"$internal/modulefixture/fixture.proto\x12\x13agentwow.fixture.v1\x1a\x1bapi/module/v1/session.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x88\x01\n" +
	"\aRequest\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x04R\x06number\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x16\n" +
	"\x06opcode\x18\x03 \x01(\rR\x06opcode\x12\x18\n" +
	"\afailure\x18\x04 \x01(\tR\afailure\x12\x19\n" +
	"\bdelay_ms\x18\x05 \x01(\rR\adelayMs\"z\n" +
	"\x06Result\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x04R\x06number\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12$\n" +
	"\x0eclient_time_ms\x18\x03 \x01(\rR\fclientTimeMs\x12\x18\n" +
	"\apackets\x18\x04 \x01(\rR\apackets2\xd4\x01\n" +
	"\aFixture\x12D\n" +
	"\aExecute\x12\x1c.agentwow.fixture.v1.Request\x1a\x1b.agentwow.fixture.v1.Result\x12C\n" +
	"\bOnPacket\x12\x1f.agentwow.module.v1.WorldPacket\x1a\x16.google.protobuf.Empty\x12>\n" +
	"\fBeforeLogout\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyBEZCgithub.com/agent-wow/agent-wow/internal/modulefixture/api;fixturev1b\x06proto3"

var (
	file_internal_modulefixture_fixture_proto_rawDescOnce sync.Once
	file_internal_modulefixture_fixture_proto_rawDescData []byte
)

func file_internal_modulefixture_fixture_proto_rawDescGZIP() []byte {
	file_internal_modulefixture_fixture_proto_rawDescOnce.Do(func() {
		file_internal_modulefixture_fixture_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_modulefixture_fixture_proto_rawDesc), len(file_internal_modulefixture_fixture_proto_rawDesc)))
	})
	return file_internal_modulefixture_fixture_proto_rawDescData
}

var file_internal_modulefixture_fixture_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_modulefixture_fixture_proto_goTypes = []any{
	(*Request)(nil),        // 0: agentwow.fixture.v1.Request
	(*Result)(nil),         // 1: agentwow.fixture.v1.Result
	(*v1.WorldPacket)(nil), // 2: agentwow.module.v1.WorldPacket
	(*emptypb.Empty)(nil),  // 3: google.protobuf.Empty
}
var file_internal_modulefixture_fixture_proto_depIdxs = []int32{
	0, // 0: agentwow.fixture.v1.Fixture.Execute:input_type -> agentwow.fixture.v1.Request
	2, // 1: agentwow.fixture.v1.Fixture.OnPacket:input_type -> agentwow.module.v1.WorldPacket
	3, // 2: agentwow.fixture.v1.Fixture.BeforeLogout:input_type -> google.protobuf.Empty
	1, // 3: agentwow.fixture.v1.Fixture.Execute:output_type -> agentwow.fixture.v1.Result
	3, // 4: agentwow.fixture.v1.Fixture.OnPacket:output_type -> google.protobuf.Empty
	3, // 5: agentwow.fixture.v1.Fixture.BeforeLogout:output_type -> google.protobuf.Empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_modulefixture_fixture_proto_init() }
func file_internal_modulefixture_fixture_proto_init() {
	if File_internal_modulefixture_fixture_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_modulefixture_fixture_proto_rawDesc), len(file_internal_modulefixture_fixture_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_modulefixture_fixture_proto_goTypes,
		DependencyIndexes: file_internal_modulefixture_fixture_proto_depIdxs,
		MessageInfos:      file_internal_modulefixture_fixture_proto_msgTypes,
	}.Build()
	File_internal_modulefixture_fixture_proto = out.File
	file_internal_modulefixture_fixture_proto_goTypes = nil
	file_internal_modulefixture_fixture_proto_depIdxs = nil
}
