// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.36.2
// source: internal/modulefixture/fixture.proto

package fixturev1

import (
	context "context"
	v1 "github.com/agent-wow/agent-wow/pkg/modules/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Fixture_Execute_FullMethodName      = "/agentwow.fixture.v1.Fixture/Execute"
	Fixture_OnPacket_FullMethodName     = "/agentwow.fixture.v1.Fixture/OnPacket"
	Fixture_BeforeLogout_FullMethodName = "/agentwow.fixture.v1.Fixture/BeforeLogout"
)

// FixtureClient is the client API for Fixture service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FixtureClient interface {
	Execute(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Result, error)
	OnPacket(ctx context.Context, in *v1.WorldPacket, opts ...grpc.CallOption) (*emptypb.Empty, error)
	BeforeLogout(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type fixtureClient struct {
	cc grpc.ClientConnInterface
}

func NewFixtureClient(cc grpc.ClientConnInterface) FixtureClient {
	return &fixtureClient{cc}
}

func (c *fixtureClient) Execute(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Result)
	err := c.cc.Invoke(ctx, Fixture_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fixtureClient) OnPacket(ctx context.Context, in *v1.WorldPacket, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Fixture_OnPacket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fixtureClient) BeforeLogout(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Fixture_BeforeLogout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FixtureServer is the server API for Fixture service.
// All implementations must embed UnimplementedFixtureServer
// for forward compatibility.
type FixtureServer interface {
	Execute(context.Context, *Request) (*Result, error)
	OnPacket(context.Context, *v1.WorldPacket) (*emptypb.Empty, error)
	BeforeLogout(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	mustEmbedUnimplementedFixtureServer()
}

// UnimplementedFixtureServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFixtureServer struct{}

func (UnimplementedFixtureServer) Execute(context.Context, *Request) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedFixtureServer) OnPacket(context.Context, *v1.WorldPacket) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnPacket not implemented")
}
func (UnimplementedFixtureServer) BeforeLogout(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BeforeLogout not implemented")
}
func (UnimplementedFixtureServer) mustEmbedUnimplementedFixtureServer() {}
func (UnimplementedFixtureServer) testEmbeddedByValue()                 {}

// UnsafeFixtureServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FixtureServer will
// result in compilation errors.
type UnsafeFixtureServer interface {
	mustEmbedUnimplementedFixtureServer()
}

func RegisterFixtureServer(s grpc.ServiceRegistrar, srv FixtureServer) {
	// If the following call pancis, it indicates UnimplementedFixtureServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Fixture_ServiceDesc, srv)
}

func _Fixture_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FixtureServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fixture_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FixtureServer).Execute(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fixture_OnPacket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.WorldPacket)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FixtureServer).OnPacket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fixture_OnPacket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FixtureServer).OnPacket(ctx, req.(*v1.WorldPacket))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fixture_BeforeLogout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FixtureServer).BeforeLogout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fixture_BeforeLogout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FixtureServer).BeforeLogout(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Fixture_ServiceDesc is the grpc.ServiceDesc for Fixture service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Fixture_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentwow.fixture.v1.Fixture",
	HandlerType: (*FixtureServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _Fixture_Execute_Handler,
		},
		{
			MethodName: "OnPacket",
			Handler:    _Fixture_OnPacket_Handler,
		},
		{
			MethodName: "BeforeLogout",
			Handler:    _Fixture_BeforeLogout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/modulefixture/fixture.proto",
}
