// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.36.2
// source: api/module/v1/session.proto

package modv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WorldPacket carries an unchanged worldserver packet to a subscribed handler.
type WorldPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Opcode        uint32                 `protobuf:"varint,1,opt,name=opcode,proto3" json:"opcode,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldPacket) Reset() {
	*x = WorldPacket{}
	mi := &file_api_module_v1_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldPacket) ProtoMessage() {}

func (x *WorldPacket) ProtoReflect() protoreflect.Message {
	mi := &file_api_module_v1_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldPacket.ProtoReflect.Descriptor instead.
func (*WorldPacket) Descriptor() ([]byte, []int) {
	return file_api_module_v1_session_proto_rawDescGZIP(), []int{0}
}

func (x *WorldPacket) GetOpcode() uint32 {
	if x != nil {
		return x.Opcode
	}
	return 0
}

func (x *WorldPacket) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// SendPacketRequest carries one outbound gameplay packet without transport framing.
type SendPacketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Opcode        uint32                 `protobuf:"varint,1,opt,name=opcode,proto3" json:"opcode,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPacketRequest) Reset() {
	*x = SendPacketRequest{}
	mi := &file_api_module_v1_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPacketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPacketRequest) ProtoMessage() {}

func (x *SendPacketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_module_v1_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPacketRequest.ProtoReflect.Descriptor instead.
func (*SendPacketRequest) Descriptor() ([]byte, []int) {
	return file_api_module_v1_session_proto_rawDescGZIP(), []int{1}
}

func (x *SendPacketRequest) GetOpcode() uint32 {
	if x != nil {
		return x.Opcode
	}
	return 0
}

func (x *SendPacketRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// ClockResponse samples the clock shared by modules and core time-sync replies.
type ClockResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Milliseconds from the session's monotonic origin, modulo 2^32.
	ClientTimeMs  uint32 `protobuf:"varint,1,opt,name=client_time_ms,json=clientTimeMs,proto3" json:"client_time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClockResponse) Reset() {
	*x = ClockResponse{}
	mi := &file_api_module_v1_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClockResponse) ProtoMessage() {}

func (x *ClockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_module_v1_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClockResponse.ProtoReflect.Descriptor instead.
func (*ClockResponse) Descriptor() ([]byte, []int) {
	return file_api_module_v1_session_proto_rawDescGZIP(), []int{2}
}

func (x *ClockResponse) GetClientTimeMs() uint32 {
	if x != nil {
		return x.ClientTimeMs
	}
	return 0
}

// InvokeModuleRequest selects a manifest-listed method on a direct dependency.
type InvokeModuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        string                 `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Request       *anypb.Any             `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeModuleRequest) Reset() {
	*x = InvokeModuleRequest{}
	mi := &file_api_module_v1_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeModuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeModuleRequest) ProtoMessage() {}

func (x *InvokeModuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_module_v1_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeModuleRequest.ProtoReflect.Descriptor instead.
func (*InvokeModuleRequest) Descriptor() ([]byte, []int) {
	return file_api_module_v1_session_proto_rawDescGZIP(), []int{3}
}

func (x *InvokeModuleRequest) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *InvokeModuleRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *InvokeModuleRequest) GetRequest() *anypb.Any {
	if x != nil {
		return x.Request
	}
	return nil
}

// InvokeModuleResponse carries the typed result without JSON conversion.
type InvokeModuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *anypb.Any             `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeModuleResponse) Reset() {
	*x = InvokeModuleResponse{}
	mi := &file_api_module_v1_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeModuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeModuleResponse) ProtoMessage() {}

func (x *InvokeModuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_module_v1_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeModuleResponse.ProtoReflect.Descriptor instead.
func (*InvokeModuleResponse) Descriptor() ([]byte, []int) {
	return file_api_module_v1_session_proto_rawDescGZIP(), []int{4}
}

func (x *InvokeModuleResponse) GetResult() *anypb.Any {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_api_module_v1_session_proto protoreflect.FileDescriptor

const file_api_module_v1_session_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/module/v1/session.proto\x12\x12agentwow.module.v1\x1a\x19google/protobuf/any.proto\x1a\x1bgoogle/protobuf/empty.proto\"?\n" +
	"\vWorldPacket\x12\x16\n" +
	"\x06opcode\x18\x01 \x01(\rR\x06opcode\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"E\n" +
	"\x11SendPacketRequest\x12\x16\n" +
	"\x06opcode\x18\x01 \x01(\rR\x06opcode\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"5\n" +
	"\rClockResponse\x12$\n" +
	"\x0eclient_time_ms\x18\x01 \x01(\rR\fclientTimeMs\"u\n" +
	"\x13InvokeModuleRequest\x12\x16\n" +
	"\x06module\x18\x01 \x01(\tR\x06module\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12.\n" +
	"\arequest\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\arequest\"D\n" +
	"\x14InvokeModuleResponse\x12,\n" +
	"\x06result\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\x06result2\x80\x02\n" +
	"\aSession\x12K\n" +
	"\n" +
	"SendPacket\x12%.agentwow.module.v1.SendPacketRequest\x1a\x16.google.protobuf.Empty\x12E\n" +
	"\bGetClock\x12\x16.google.protobuf.Empty\x1a!.agentwow.module.v1.ClockResponse\x12a\n" +
	"\fInvokeModule\x12'.agentwow.module.v1.InvokeModuleRequest\x1a(.agentwow.module.v1.InvokeModuleResponseB3Z1github.com/hazim-j/agent-wow/pkg/modules/v1;modv1b\x06proto3"

var (
	file_api_module_v1_session_proto_rawDescOnce sync.Once
	file_api_module_v1_session_proto_rawDescData []byte
)

func file_api_module_v1_session_proto_rawDescGZIP() []byte {
	file_api_module_v1_session_proto_rawDescOnce.Do(func() {
		file_api_module_v1_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_module_v1_session_proto_rawDesc), len(file_api_module_v1_session_proto_rawDesc)))
	})
	return file_api_module_v1_session_proto_rawDescData
}

var file_api_module_v1_session_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_module_v1_session_proto_goTypes = []any{
	(*WorldPacket)(nil),          // 0: agentwow.module.v1.WorldPacket
	(*SendPacketRequest)(nil),    // 1: agentwow.module.v1.SendPacketRequest
	(*ClockResponse)(nil),        // 2: agentwow.module.v1.ClockResponse
	(*InvokeModuleRequest)(nil),  // 3: agentwow.module.v1.InvokeModuleRequest
	(*InvokeModuleResponse)(nil), // 4: agentwow.module.v1.InvokeModuleResponse
	(*anypb.Any)(nil),            // 5: google.protobuf.Any
	(*emptypb.Empty)(nil),        // 6: google.protobuf.Empty
}
var file_api_module_v1_session_proto_depIdxs = []int32{
	5, // 0: agentwow.module.v1.InvokeModuleRequest.request:type_name -> google.protobuf.Any
	5, // 1: agentwow.module.v1.InvokeModuleResponse.result:type_name -> google.protobuf.Any
	1, // 2: agentwow.module.v1.Session.SendPacket:input_type -> agentwow.module.v1.SendPacketRequest
	6, // 3: agentwow.module.v1.Session.GetClock:input_type -> google.protobuf.Empty
	3, // 4: agentwow.module.v1.Session.InvokeModule:input_type -> agentwow.module.v1.InvokeModuleRequest
	6, // 5: agentwow.module.v1.Session.SendPacket:output_type -> google.protobuf.Empty
	2, // 6: agentwow.module.v1.Session.GetClock:output_type -> agentwow.module.v1.ClockResponse
	4, // 7: agentwow.module.v1.Session.InvokeModule:output_type -> agentwow.module.v1.InvokeModuleResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_module_v1_session_proto_init() }
func file_api_module_v1_session_proto_init() {
	if File_api_module_v1_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_module_v1_session_proto_rawDesc), len(file_api_module_v1_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_module_v1_session_proto_goTypes,
		DependencyIndexes: file_api_module_v1_session_proto_depIdxs,
		MessageInfos:      file_api_module_v1_session_proto_msgTypes,
	}.Build()
	File_api_module_v1_session_proto = out.File
	file_api_module_v1_session_proto_goTypes = nil
	file_api_module_v1_session_proto_depIdxs = nil
}
