// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.36.2
// source: api/module/v1/session.proto

package modv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Session_SendPacket_FullMethodName   = "/agentwow.module.v1.Session/SendPacket"
	Session_GetClock_FullMethodName     = "/agentwow.module.v1.Session/GetClock"
	Session_InvokeModule_FullMethodName = "/agentwow.module.v1.Session/InvokeModule"
)

// SessionClient is the client API for Session service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Session exposes callbacks on each module's session-owned socket.
type SessionClient interface {
	// SendPacket confirms a transport write, not server acceptance. Never retry automatically.
	SendPacket(ctx context.Context, in *SendPacketRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// GetClock returns the shared monotonic session clock.
	GetClock(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ClockResponse, error)
	// InvokeModule forwards a typed call to a dependency. Preserve ctx for nested calls.
	InvokeModule(ctx context.Context, in *InvokeModuleRequest, opts ...grpc.CallOption) (*InvokeModuleResponse, error)
}

type sessionClient struct {
	cc grpc.ClientConnInterface
}

func NewSessionClient(cc grpc.ClientConnInterface) SessionClient {
	return &sessionClient{cc}
}

func (c *sessionClient) SendPacket(ctx context.Context, in *SendPacketRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Session_SendPacket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionClient) GetClock(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ClockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClockResponse)
	err := c.cc.Invoke(ctx, Session_GetClock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionClient) InvokeModule(ctx context.Context, in *InvokeModuleRequest, opts ...grpc.CallOption) (*InvokeModuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvokeModuleResponse)
	err := c.cc.Invoke(ctx, Session_InvokeModule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SessionServer is the server API for Session service.
// All implementations must embed UnimplementedSessionServer
// for forward compatibility.
//
// Session exposes callbacks on each module's session-owned socket.
type SessionServer interface {
	// SendPacket confirms a transport write, not server acceptance. Never retry automatically.
	SendPacket(context.Context, *SendPacketRequest) (*emptypb.Empty, error)
	// GetClock returns the shared monotonic session clock.
	GetClock(context.Context, *emptypb.Empty) (*ClockResponse, error)
	// InvokeModule forwards a typed call to a dependency. Preserve ctx for nested calls.
	InvokeModule(context.Context, *InvokeModuleRequest) (*InvokeModuleResponse, error)
	mustEmbedUnimplementedSessionServer()
}

// UnimplementedSessionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSessionServer struct{}

func (UnimplementedSessionServer) SendPacket(context.Context, *SendPacketRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendPacket not implemented")
}
func (UnimplementedSessionServer) GetClock(context.Context, *emptypb.Empty) (*ClockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClock not implemented")
}
func (UnimplementedSessionServer) InvokeModule(context.Context, *InvokeModuleRequest) (*InvokeModuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InvokeModule not implemented")
}
func (UnimplementedSessionServer) mustEmbedUnimplementedSessionServer() {}
func (UnimplementedSessionServer) testEmbeddedByValue()                 {}

// UnsafeSessionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SessionServer will
// result in compilation errors.
type UnsafeSessionServer interface {
	mustEmbedUnimplementedSessionServer()
}

func RegisterSessionServer(s grpc.ServiceRegistrar, srv SessionServer) {
	// If the following call pancis, it indicates UnimplementedSessionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Session_ServiceDesc, srv)
}

func _Session_SendPacket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendPacketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServer).SendPacket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Session_SendPacket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServer).SendPacket(ctx, req.(*SendPacketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Session_GetClock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServer).GetClock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Session_GetClock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServer).GetClock(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Session_InvokeModule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeModuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServer).InvokeModule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Session_InvokeModule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServer).InvokeModule(ctx, req.(*InvokeModuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Session_ServiceDesc is the grpc.ServiceDesc for Session service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Session_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentwow.module.v1.Session",
	HandlerType: (*SessionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendPacket",
			Handler:    _Session_SendPacket_Handler,
		},
		{
			MethodName: "GetClock",
			Handler:    _Session_GetClock_Handler,
		},
		{
			MethodName: "InvokeModule",
			Handler:    _Session_InvokeModule_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/module/v1/session.proto",
}
