// Command mapcatalog generates stock build-12340 English map and zone labels
// from local Map.dbc and AreaTable.dbc reference files. It does not access the
// network or server internals. Run from the repository root:
//
//	./run client-data:fetch
//	./run mapcatalog:generate
package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/binary"
	"errors"
	"fmt"
	"go/format"
	"os"
	"slices"
	"unicode"
	"unicode/utf8"

	"github.com/agent-wow/agent-wow/tools/internal/clientdata"
)

const destination = "pkg/maps/labels_gen.go"

func main() {
	if len(os.Args) == 2 && (os.Args[1] == "--help" || os.Args[1] == "-h") {
		fmt.Println("Usage: ./run mapcatalog:generate\nReads tmp/client-data and writes pkg/maps/labels_gen.go. Run './run client-data:fetch' first.")
		return
	}
	if len(os.Args) != 1 {
		fmt.Fprintln(os.Stderr, "Usage: ./run mapcatalog:generate")
		os.Exit(2)
	}
	data, err := generate(clientdata.Directory)
	if err == nil {
		err = os.WriteFile(destination, data, 0o644)
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "generate map catalogue:", err)
		os.Exit(1)
	}
	fmt.Printf("Generated %s (%d bytes)\n", destination, len(data))
}

func generate(directory string) ([]byte, error) {
	var out bytes.Buffer
	fmt.Fprintln(&out, "// Code generated by ./run mapcatalog:generate; DO NOT EDIT.")
	fmt.Fprintln(&out, "// WoW 3.3.5a, build 12340, enUS.")
	fmt.Fprintln(&out, "// Source: "+clientdata.ReleaseURL)
	fmt.Fprintln(&out, "// Field layouts: https://github.com/wowdev/WoWDBDefs/tree/master/definitions")
	fmt.Fprintln(&out, "\npackage maps")
	for _, table := range []struct {
		file, variable string
		fields, label  uint32
	}{
		{"Map.dbc", "mapNames", 66, 5},
		{"AreaTable.dbc", "zoneNames", 36, 11},
	} {
		data, err := clientdata.Read(directory, table.file)
		if err != nil {
			return nil, err
		}
		labels, err := decodeLabels(data, table.fields, table.label)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", table.file, err)
		}
		fmt.Fprintf(&out, "\n// %s: %d labels; SHA-256: %x\n", table.file, len(labels), sha256.Sum256(data))
		fmt.Fprintf(&out, "var %s = map[uint32]string{\n", table.variable)
		ids := make([]uint32, 0, len(labels))
		for id := range labels {
			ids = append(ids, id)
		}
		slices.Sort(ids)
		for _, id := range ids {
			fmt.Fprintf(&out, "%d: %q,\n", id, labels[id])
		}
		fmt.Fprintln(&out, "}")
	}
	return format.Source(out.Bytes())
}

func decodeLabels(data []byte, fields, labelField uint32) (map[uint32]string, error) {
	if len(data) < 20 || string(data[:4]) != "WDBC" {
		return nil, errors.New("expected a complete WDBC header")
	}
	count := binary.LittleEndian.Uint32(data[4:8])
	columns := binary.LittleEndian.Uint32(data[8:12])
	size := binary.LittleEndian.Uint32(data[12:16])
	stringsSize := binary.LittleEndian.Uint32(data[16:20])
	if columns != fields || uint64(size) != uint64(fields)*4 || labelField >= fields {
		return nil, errors.New("unexpected DBC field layout")
	}
	// Validate using uint64 before converting header lengths to slice indexes.
	stringsStart := 20 + uint64(count)*uint64(size)
	if stringsStart+uint64(stringsSize) != uint64(len(data)) {
		return nil, errors.New("file length does not match DBC record and string counts")
	}
	if count == 0 {
		return nil, errors.New("DBC has no records")
	}
	strings := data[int(stringsStart):]
	labels := make(map[uint32]string, int(count))
	for i := uint32(0); i < count; i++ {
		start := 20 + int(i)*int(size)
		id := binary.LittleEndian.Uint32(data[start : start+4])
		labelStart := start + int(labelField)*4
		offset := binary.LittleEndian.Uint32(data[labelStart : labelStart+4])
		if uint64(offset) >= uint64(len(strings)) {
			return nil, fmt.Errorf("ID %d: label offset outside string block", id)
		}
		end := bytes.IndexByte(strings[int(offset):], 0)
		if end < 0 {
			return nil, fmt.Errorf("ID %d: unterminated label", id)
		}
		label := strings[int(offset) : int(offset)+end]
		if len(label) == 0 || !utf8.Valid(label) || bytes.IndexFunc(label, unicode.IsControl) >= 0 {
			return nil, fmt.Errorf("ID %d: expected a nonempty English label without control characters", id)
		}
		if _, exists := labels[id]; exists {
			return nil, fmt.Errorf("duplicate ID %d", id)
		}
		labels[id] = string(label)
	}
	return labels, nil
}
